### PR TITLE
Remember Contributer Name & Keys Tried formatting

### PR DESCRIPTION
**Pull request by CypherX**
Added functionality to remember the entered Contributer Name and load it upon opening the application. Also changed the type of TotalCount from int to long to prevent overflow errors and added formatting (commas) to the Keys Tried output on the form.

### CODE REVIEW

**Comment by CypherX** [comment]
Fixes for Issues #3 and #4

**Comment by TheRealDF** [comment]
Sorry for the delay! Been hard at work on this.

Sadly there are too many conflicts with the current version now that would break the build and my local version if accepted. If you don't mind, please pull down the latest, apply your changes and resubmit so i can accept them asap.

**Review by TheRealDF — CHANGES_REQUESTED** [review]
refer to last comment made.

**Comment by CypherX** [comment]
See PR #9 for updated build

**Pull request closed without merging**
