### PR TITLE
Quality of life changes, Persisting settings, bug fixes

### PR DESCRIPTION
**Pull request by CypherX**
Persist Contribute Name and CPU Power settings through application restarts
Disable certain controls during brute force loop
Fix overflow error on TotalCount var
Format Approx. Keys Tried & Good Keys output
Set Results and News textboxes to readonly
Misc. fixes

### CODE REVIEW

**Comment by TheRealDF** [comment]
It seems that the branch still has conflicts. If you can please try to rectify this and I'll accept the push. Currently on mobile so I can look much into it

**Review by TheRealDF — CHANGES_REQUESTED** [review]
Refer to last comment

**Comment by CypherX** [comment]
Wat. That's really weird. Said there were no conflicts when I created it. Will have to look at later, busy playing Overwatch right now.

**Comment by CypherX** [comment]
Oh it's because you merged the other PR. Gotcha,

**Comment by TheRealDF** [comment]
Ya sorry about that :/  been hectic over here.

**Comment by Javano** [comment]
Since there's some overlap, figured I'd just clarify that you don't need to worry about reimplementing the following features, as they were already included in my pull:
- Disable certain controls during brute force loop
- Format Approx. Keys Tried & Good Keys output
- Set Results and News textboxes to readonly

Not sure how far you are with this, but hopefully that saves you some time. :)

**Comment by CypherX** [comment]
Yeah, I saw the changes included in yours, just been busy with work so haven't had time to update mine. Closing this PR now to open a new one with the remaining changes.

**Pull request closed without merging**
